version: '3.9'

services:
  movies-api:
    build: 
      context: ../
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=server.pfx
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;
      - 'ConnectionStrings__MongoDb=mongodb://root:S3cr3t!@mongo/Movies?authSource=admin'
      - WAIT_HOSTS=mongo:27017
    volumes:
      - ../ssl/server.pfx:/app/server.pfx
    ports:
      - 44300:443
    depends_on:
      - mongo