version: "3.9"

services:
  angularclient:
    build:
      context: ../
      dockerfile: src/AngularApp/Dockerfile
    environment:
      - WAIT_HOSTS=movies-api:44300
      - GRAPHQL_URL=https://localhost:44300/graphql
    volumes:
      - ../ssl:/ssl
    ports:
      - 44399:8443
    depends_on:
      - movies-api
  reactclient:
    build:
      context: ../
      dockerfile: src/reactapp/Dockerfile
    environment:
      - WAIT_HOSTS=movies-api:44300
    volumes:
      - ../ssl:/ssl
    ports:
      - 44398:8443
    depends_on:
      - movies-api
